name: Blocks
version: '${project.version}'
main: xyz.szambo.blocks.Main
api-version: 1.16
authors: [ Szamboniarzyk ]
description: Simple Blocks plugin

commands:
  blocks:
    aliases:
      - bloki
      - block
